/** Maximum number of articles in the list (for extract / reference list). */
export const MAX_PAPERS = 10;

/**
 * Extraction field keys; must match backend EXTRACTION_FIELDS.
 */
export const EXTRACTION_FIELDS = [
  'Citation',
  'Study ID',
  'Authors',
  'Year',
  'Country/Region',
  'Funding Source',
  'Study Design',
  'Population/Setting',
  'Sample Size (N)',
  'Mean Age (SD)',
  'Gender Breakdown',
  'Inclusion Criteria',
  'Exclusion Criteria',
  'Recruitment Method',
  'Intervention Name',
  'Intervention Description',
  'Intervention Frequency',
  'Intervention Duration',
  'Delivery Mode (paper/app/online)',
  'Comparator/Control',
  'Adherence/Fidelity Monitoring',
  'Primary Outcomes',
  'Secondary Outcomes',
  'Outcome Measures/Scales',
  'Assessment Timepoints (baseline, post, follow-up)',
  'Statistical Analyses',
  'Effect Sizes (with CI)',
  'Mediators Tested',
  'Moderators Tested',
  'Main Results/Findings',
  'Harms/Adverse Events',
  'RoB: Incomplete Outcome Data',
  'Strengths',
  'Limitations',
  "Authors' Stated Gaps/Future Research",
  'Practical Implications',
  'Notes/Relevance to My Study',
];
